export const MODEL_14_FEATURES = [
  'RepairAuthorized',
  'SerialNumberMatch',
  'ProductModelConsistent',
  'DuplicateClaimIndicator',
  'ContradictionIndicator',
  'OCRConfidence',
  'ClaimReportingDelayDays',
  'WarrantyRemainingDays',
  'ClaimReportingWithinPeriod',
  'FaultCovered',
  'RequiredDocumentsComplete',
  'MissingDocumentCount',
  'ProductIdentityMatch',
  'OCRQualityBand',
]

export const claim14FieldGroups = [
  {
    title: 'Product & Identity Verification',
    description: 'Verify product identity, serial number consistency, and equipment authenticity',
    fields: [
      {
        name: 'ProductIdentityMatch',
        label: 'Product Identity Match',
        viLabel: 'Product Identity Match',
        type: 'select',
        options: ['Yes', 'No'],
        default: 'Yes',
        help: 'Whether product model on file matches the registered device',
      },
      {
        name: 'SerialNumberMatch',
        label: 'Serial Number Match',
        viLabel: 'Serial Number Match',
        type: 'select',
        options: ['Yes', 'No', 'Unknown'],
        default: 'Yes',
        help: 'Whether the physical device serial matches the warranty receipt',
      },
      {
        name: 'ProductModelConsistent',
        label: 'Product Model Consistent',
        viLabel: 'Product Model Consistent',
        type: 'select',
        options: ['Yes', 'No'],
        default: 'Yes',
        help: 'Consistency of product model specification across documentation',
      },
    ],
  },
  {
    title: 'Warranty Status & Coverage',
    description: 'Remaining warranty period, policy coverage scope, and reporting timeliness',
    fields: [
      {
        name: 'WarrantyRemainingDays',
        label: 'Warranty Remaining Days',
        viLabel: 'Warranty Remaining Days',
        type: 'number',
        step: 1,
        default: 180,
        help: 'Active days remaining on coverage (>= 0 is active, < 0 is expired)',
      },
      {
        name: 'FaultCovered',
        label: 'Fault Covered by Policy',
        viLabel: 'Fault Covered by Policy',
        type: 'select',
        options: ['Yes', 'No', 'Unknown'],
        default: 'Yes',
        help: 'Manufacturer hardware defect (Yes) or accidental damage / liquid ingress (No)',
      },
      {
        name: 'ClaimReportingDelayDays',
        label: 'Reporting Delay Days',
        viLabel: 'Reporting Delay Days',
        type: 'number',
        min: 0,
        step: 1,
        default: 5,
        help: 'Elapsed days between hardware fault occurrence and claim submission',
      },
      {
        name: 'ClaimReportingWithinPeriod',
        label: 'Claim Reporting Within Period',
        viLabel: 'Claim Reporting Within Period',
        type: 'select',
        options: ['Yes', 'No', 'Unknown'],
        default: 'Yes',
        help: 'Whether the claim was submitted within the statutory 30-day window',
      },
    ],
  },
  {
    title: 'Repair History & Integrity',
    description: 'Service center authorization and fraud/anomaly indicators',
    fields: [
      {
        name: 'RepairAuthorized',
        label: 'Repair Authorized',
        viLabel: 'Repair Authorized',
        type: 'select',
        options: ['Yes', 'No', 'Not Applicable', 'Unknown'],
        default: 'Not Applicable',
        help: 'Prior service performed by an authorized OEM service partner',
      },
      {
        name: 'DuplicateClaimIndicator',
        label: 'Duplicate Claim Indicator',
        viLabel: 'Duplicate Claim Indicator',
        type: 'select',
        options: ['No', 'Yes'],
        default: 'No',
        help: 'Automated detection flag for duplicate claim filings',
      },
      {
        name: 'ContradictionIndicator',
        label: 'Contradiction Indicator',
        viLabel: 'Contradiction Indicator',
        type: 'select',
        options: ['No', 'Yes'],
        default: 'No',
        help: 'Discrepancies detected between statement and diagnostic logs',
      },
    ],
  },
  {
    title: 'Documents & OCR Quality',
    description: 'Document completeness and automated OCR extraction confidence',
    fields: [
      {
        name: 'RequiredDocumentsComplete',
        label: 'Required Documents Complete',
        viLabel: 'Required Documents Complete',
        type: 'select',
        options: ['Yes', 'No', 'Unknown'],
        default: 'Yes',
        help: 'All statutory proof of purchase and warranty certificates provided',
      },
      {
        name: 'MissingDocumentCount',
        label: 'Missing Document Count',
        viLabel: 'Missing Document Count',
        type: 'number',
        min: 0,
        step: 1,
        default: 0,
        help: 'Count of mandatory documentation items missing',
      },
      {
        name: 'OCRConfidence',
        label: 'OCR / Document Confidence Score',
        viLabel: 'OCR / Document Confidence Score',
        type: 'number',
        min: 0,
        max: 1,
        step: 0.01,
        default: 0.90,
        help: 'Document text recognition and invoice stamp verification score',
      },
      {
        name: 'OCRQualityBand',
        label: 'OCR Quality Band',
        viLabel: 'OCR Quality Band',
        type: 'select',
        options: ['High', 'Medium', 'Low', 'Missing'],
        default: 'High',
        help: 'Clarity rating: High (>= 0.85), Medium (0.65 - 0.85), Low (< 0.65)',
      },
    ],
  },
]

// Legacy alias for existing App.jsx MLClassification
export const claimFieldGroups = claim14FieldGroups

export const CLAIM_PRESETS = [
  {
    id: 'valid',
    badge: 'Valid',
    name: 'Valid Claim (Standard OEM)',
    tone: 'success',
    description: 'Within warranty period, manufacturer hardware defect, complete documentation, high OCR quality',
    features: {
      ProductIdentityMatch: 'Yes',
      SerialNumberMatch: 'Yes',
      ProductModelConsistent: 'Yes',
      WarrantyRemainingDays: 180,
      FaultCovered: 'Yes',
      ClaimReportingDelayDays: 3,
      ClaimReportingWithinPeriod: 'Yes',
      RepairAuthorized: 'Not Applicable',
      DuplicateClaimIndicator: 'No',
      ContradictionIndicator: 'No',
      RequiredDocumentsComplete: 'Yes',
      MissingDocumentCount: 0,
      OCRConfidence: 0.95,
      OCRQualityBand: 'High',
    },
    meta: {
      product_type: 'Laptop',
      product_model: 'Lenovo ThinkPad T14 Gen 4',
      order_code: 'ORD-2026-88192',
      problem_category: 'Screen / Display',
      problem_description: 'Screen flickering with horizontal lines continuously after startup, device has no physical impact or liquid damage, 180 days manufacturer warranty remaining.',
    },
  },
  {
    id: 'review',
    badge: 'Review',
    name: 'Manual Review (Requires Examination)',
    tone: 'warning',
    description: 'Serial number unclear, medium OCR confidence, reporting delay, reviewer inspection recommended',
    features: {
      ProductIdentityMatch: 'Yes',
      SerialNumberMatch: 'Unknown',
      ProductModelConsistent: 'Yes',
      WarrantyRemainingDays: 15,
      FaultCovered: 'Yes',
      ClaimReportingDelayDays: 25,
      ClaimReportingWithinPeriod: 'Yes',
      RepairAuthorized: 'Unknown',
      DuplicateClaimIndicator: 'No',
      ContradictionIndicator: 'No',
      RequiredDocumentsComplete: 'Unknown',
      MissingDocumentCount: 1,
      OCRConfidence: 0.72,
      OCRQualityBand: 'Medium',
    },
    meta: {
      product_type: 'Smartphone',
      product_model: 'Samsung Galaxy S24 Ultra',
      order_code: 'ORD-2026-44102',
      problem_category: 'Battery',
      problem_description: 'Battery drains rapidly and overheats unusually following a software update, serial number on receipt slightly blurred and requires reviewer verification.',
    },
  },
  {
    id: 'invalid',
    badge: 'Reject',
    name: 'Invalid Claim (Ineligible / Policy Exclusion)',
    tone: 'danger',
    description: 'Expired warranty, accidental drop / liquid intrusion damage, duplicate claim detected',
    features: {
      ProductIdentityMatch: 'No',
      SerialNumberMatch: 'No',
      ProductModelConsistent: 'No',
      WarrantyRemainingDays: -45,
      FaultCovered: 'No',
      ClaimReportingDelayDays: 90,
      ClaimReportingWithinPeriod: 'No',
      RepairAuthorized: 'No',
      DuplicateClaimIndicator: 'Yes',
      ContradictionIndicator: 'Yes',
      RequiredDocumentsComplete: 'No',
      MissingDocumentCount: 3,
      OCRConfidence: 0.38,
      OCRQualityBand: 'Low',
    },
    meta: {
      product_type: 'Tablet',
      product_model: 'iPad Pro 11-inch M2',
      order_code: 'ORD-2025-11094',
      problem_category: 'Physical Damage',
      problem_description: 'Device suffered screen shatter and displays signs of water immersion, previously serviced by an unauthorized repair facility.',
    },
  },
]

